# Generated by Django 5.1.8 on 2025-05-21 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0005_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='message',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='role',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='stars',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content',
            field=models.TextField(default='Default content'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 21, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(default='Default title', max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='testimonials/default.jpg', upload_to='testimonials/'),
            preserve_default=False,
        ),
    ]
