# Generated by Django 5.1.8 on 2025-05-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0006_remove_testimonial_message_remove_testimonial_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
