# Generated by Django 5.1.8 on 2025-05-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0007_delete_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
    ]
