# Generated by Django 5.1.8 on 2025-05-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0008_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='rating',
        ),
    ]
