# Generated by Django 5.1.8 on 2025-05-27 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0012_jobopening'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('experience', models.CharField(choices=[('Fresher', 'Fresher'), ('1-3 Years', '1-3 Years'), ('3-5 Years', '3-5 Years'), ('Other', 'Other')], max_length=20)),
                ('experience_other', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_status', models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student')], max_length=20)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.jobopening')),
            ],
        ),
    ]
