# Generated by Django 5.1.8 on 2025-05-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0013_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='experience_other',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='employment_status',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Self-Employed', 'Self-Employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('1-3 Years', '1-3 Years'), ('3-5 Years', '3-5 Years'), ('5+ Years', '5+ Years')], max_length=20),
        ),
    ]
